CREATE TABLE "users" (
	"uid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_uid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999999 START WITH 1 CACHE 1),
	"nickname" varchar(16) NOT NULL,
	"discriminator" smallint NOT NULL,
	"role" varchar(16) DEFAULT 'user' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_nickname_discriminator_unique" UNIQUE("nickname","discriminator"),
	CONSTRAINT "users_uid_range_check" CHECK ("users"."uid" BETWEEN 0 AND 99999999),
	CONSTRAINT "users_discriminator_range_check" CHECK ("users"."discriminator" BETWEEN 0 AND 9999),
	CONSTRAINT "users_role_check" CHECK ("users"."role" IN ('user', 'admin')),
	CONSTRAINT "users_nickname_not_blank_check" CHECK (char_length(btrim("users"."nickname")) > 0),
	CONSTRAINT "users_reserved_zero_identity_check" CHECK ((
        (
          "users"."uid" = 0
          AND "users"."discriminator" = 0
          AND "users"."role" = 'admin'
        )
        OR
        (
          "users"."uid" > 0
          AND "users"."discriminator" > 0
        )
      ))
);
